### PR TITLE
Fix chooser tabs compatibility with Wagtail 3.0, and drop Wagtail < 2.15

### LINKED ISSUE #157: Expected UI issues with Wagtail 3.0 release
The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

In the case of wagtailmedia, the only issue is reliance on Wagtail’s internal tabs implementation:

```text
torchbox/wagtailmedia/src/wagtailmedia/templates/wagtailmedia/chooser/chooser.html
15:    <ul class="tab-nav merged" data-tab-nav>
```

Here is our [guidance on replacing Bootstrap tabs](https://github.com/wagtail/wagtail/discussions/7739#user-content-2022-04-22-breaking-changes-in-ui-code-bootstrap-tabs), and our [proposal for a tabs component API](https://github.com/wagtail/wagtail/issues/8408).

### LINKED ISSUE #160: Attribute error with plain custom media model
### Issue Summary

When setting wagtailmedia up with custom media model I and click the "add video" button, I get the following error:
`type object 'CustomMedia' has no attribute 'admin_form_fields'`

### Steps to Reproduce

* Setup wagtailmedia in a Wagtail project
* Configure a plain custom media model like this:
    ```
    from wagtailmedia import models as media_models


    class CustomMedia(media_models.AbstractMedia):
        pass
    ```
* Open the Wagtail admin
* Navigate to the "media" screen
* Click the "add video" button

To fix this issue I need to use:

```
class CustomMedia(media_models.AbstractMedia):
    admin_form_fields = media_models.Media.admin_form_fields

```

I wonder if the fields should be added to the `AbstractMedia` model, or if we should update the instructions in the README to work with a custom media model. 

### Technical details

* Python version: 3.9.13
* Django version: 4.0.4
* Wagtail version: 2.16.2
* `wagtailmedia` version: 0.9.0
* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.

### PR DESCRIPTION
**Pull request by zerolab**
This PR:

- Fixes #157 - mainly backports and tweaks the tabs.js implementation in Wagtail 3.0 and updates the markup accordingly in a separate template
- Fixes #160 - no reason not to move `admin_form_fields` to the abstract model
- Drops support for Wagtail < 2.15, Django < 3.2
- tidies up usages of `six.b`

### CODE REVIEW

File: src/wagtailmedia/static/wagtailmedia/js/tabs.js [hunk 1]
```diff
@@ -0,0 +1,365 @@
+/**
```
Comment (zerolab) [inline src/wagtailmedia/static/wagtailmedia/js/tabs.js:1]: @thibaudcolas any reason not to use the non-transpiled ES6 version given that we dropped IE11 support in 2.15?

File: src/wagtailmedia/templates/wagtailmedia/chooser/chooser-next.html [hunk 2]
```diff
@@ -0,0 +1,90 @@
+{% load i18n wagtailadmin_tags %}
+{% trans "Choose a media file" as  choose_str %}
+{% include "wagtailadmin/shared/header.html" with title=choose_str merged=1 icon="media" %}
+
+{# TODO: drop data-wmtabs and the tabs.js include when a better tabs framework is in place #}
+<div class="w-tabs" data-tabs data-tabs-animate data-wm-tabs>
```
Comment (th3hamm0r) [inline src/wagtailmedia/templates/wagtailmedia/chooser/chooser-next.html:6]:
```suggestion
<div class="w-tabs" data-tabs data-tabs-animate data-tabs-disable-url data-wm-tabs>
```
This is analog to the image's/document's chooser.
Currently, without the `data-tabs-disable-url`, if you open the media chooser, click "Upload Audio", `#tab-upload-audio` gets added to the browser location, if you now reload the page, and then reopen the media chooser, in my case, I see blank areas around the upload form, so I have to scroll down a bit. So the chooser without this option seems to be a bit buggy.

File: src/wagtailmedia/templates/wagtailmedia/chooser/chooser-next.html [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+                    {% endif %}
+                </ul>
+            </form>
+            <div id="search-results" class="listing media">
+                {% include "wagtailmedia/chooser/results.html" %}
+            </div>
+        </section>
+        {% if uploadforms %}
+            {% for form_type, uploadform in uploadforms.items %}
+            <section id="tab-upload-{{ form_type }}" class="w-tabs__panel" role="tabpanel" aria-labelledby="tab-label-upload-{{ form_type }}">
```
Comment (th3hamm0r) [inline src/wagtailmedia/templates/wagtailmedia/chooser/chooser-next.html:68]:
```suggestion
            <section id="tab-upload-{{ form_type }}" class="w-tabs__panel" role="tabpanel" aria-labelledby="tab-label-upload-{{ form_type }}" hidden>
```
This is also analog to the image's/document's chooser and this was actually the cause for the blanks, noted in the above issue with `data-tabs-disable-url`. It also caused some blanks added to the bottom if the chooser was initially opened.
I think adding `data-tabs-disable-url` still seems better, so its similar to the other choosers, and also keeping the hash in the url makes no sense to me, because normally you will choose an upload tab, upload the file, which closes the chooser. Now the hash is still in the browsers location...

**Comment by th3hamm0r** [comment]
With those two additional attributes in the `chooser-next.html` it looks good to me.
Tested it with Firefox 101 and Chrome 102.

File: src/wagtailmedia/views/chooser.py [hunk 4]
```diff
@@ -116,7 +117,9 @@ def chooser(request, media_type=None):
 
     return render_modal_workflow(
         request,
-        "wagtailmedia/chooser/chooser.html",
+        "wagtailmedia/chooser/chooser-next.html"
+        if WAGTAIL_VERSION >= (3, 0)
+        else "wagtailmedia/chooser/chooser.html",
```
[the remark this answers is not in the document]
Comment (zerolab) [reply src/wagtailmedia/views/chooser.py]: done in [37aff9e](https://github.com/torchbox/wagtailmedia/pull/161/commits/37aff9e3ec2891323607b4e1500b949ccfda1676)
